language: node_js
node_js:
- "0.11"
env:
  matrix:
  - JOB=unit-stable
    CHANNEL=stable
    TESTS=dart2js
  - JOB=unit-dev
    CHANNEL=dev
    TESTS=dart2js
  - JOB=unit-dev
    CHANNEL=dev
    TESTS=vm
  - JOB=unit-stable
    CHANNEL=stable
    TESTS=vm

before_install:
- export DISPLAY=:99.0
- ./travis/install.sh
before_script:
- ./travis/setup.sh
script:
- ./travis/build.sh
