name: cogito
description: A web based tool for planing and design
dependencies:
  angular:
    git: https://github.com/angular/angular.dart.git
  browser: any
  mongo_dart: any
  quiver: any
  RestLibrary:
    git: https://github.com/Pajn/RestLibrary.git
  shadow_dom: any
dev_dependencies:
  guinness: ">=0.0.1 <1.0.0"
  matcher: any
  unittest: any
transformers:
- angular:
    html_files:
      - web/lib/components/page/page.html
      - web/lib/components/panel/panel.html
