name: cogito
description: A web based tool for planing and design
dependencies:
  angular:
    git: https://github.com/angular/angular.dart.git
  animation: any
  browser: any
  crypto: any
  dbcrypt: any
  mongo_dart: any
  quiver: any
  RestLibrary:
    git: https://github.com/Pajn/RestLibrary.git
  shadow_dom: any
dev_dependencies:
  guinness: ">=0.1.3"
  matcher: any
  mock: any
  unittest: any
transformers:
- angular:
    html_files:
      - web/views/login.html
      - web/lib/components/dropdown/dropdown.html
      - web/lib/components/loading/loading.html
      - web/lib/components/modal/modal.html
      - web/lib/components/notifications/notifications.html
      - web/lib/components/page/page.html
      - web/lib/components/panel/panel.html
      - web/lib/components/popup_menu/popup_menu.html
- $dart2js:
    checked: false
    minify: true
    verbose: true
    analyzeAll: false
    suppressWarnings: false
    suppressHints: false
    terse: false
