name: cogito
description: A web based tool for planing and design
dependencies:
  angular: 0.10.0
  browser: any
  mongo_dart: any
  quiver: any
  RestLibrary:
    git: https://github.com/Pajn/RestLibrary.git
  shadow_dom: any
dev_dependencies:
  unittest: any
transformers:
- angular:
    html_files:
      - web/lib/components/page/page.html
      - web/lib/components/panel/panel.html
