name: cogito
description: A web based tool for planing and design
dependencies:
  angular:
    git: https://github.com/angular/angular.dart.git
  browser: any
  mongo_dart: any
  quiver: any
  RestLibrary:
    git: https://github.com/Pajn/RestLibrary.git
  shadow_dom: any
dev_dependencies:
  dart_to_js_script_rewriter: any
  guinness: ">=0.1.3"
  matcher: any
  unittest: any
transformers:
- angular:
    html_files:
      - web/lib/components/page/page.html
      - web/lib/components/panel/panel.html
- dart_to_js_script_rewriter
- $dart2js:
    checked: false
    minify: true
    verbose: true
    analyzeAll: false
    suppressWarnings: false
    suppressHints: false
    terse: false
